wandb_version: 1

model Architecture:
  desc: null
  value: Unet++
encoder:
  desc: null
  value: efficientnet_b3
freeze encoder:
  desc: null
  value: false
augmentation:
  desc: null
  value: false
batch size:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 30
criterion:
  desc: null
  value: Cross Entropy
scheduler:
  desc: null
  value: Reduce on Plateau
model weight:
  desc: null
  value: model_upp_eff3_noaug_schlrP_30eps_2023_12_19_020430.pth
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702922670.952262
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
